export const RATE_LOAD_MORE_BEGIN = 'RATE_LOAD_MORE_BEGIN';
export const RATE_LOAD_MORE_SUCCESS = 'RATE_LOAD_MORE_SUCCESS';
export const RATE_LOAD_MORE_FAILURE = 'RATE_LOAD_MORE_FAILURE';
export const RATE_LOAD_MORE_DISMISS_ERROR = 'RATE_LOAD_MORE_DISMISS_ERROR';
